function [fitresult, gof] = createFit(w, S21, C)
%CREATEFIT(W,S21)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : w
%      Y Output: S21
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Dec-2021 14:06:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( w, S21);

% Set up fittype and options.
ft = fittype( '20*log10(abs((2*((L+L1)./(C)-w.^2*L*L1)./(j*w*L+1./(j*w*C)))./(Zo+2*((L+L1)./(C)-w.^2*L*L1)./(j*w*L+1./(j*w*C)))));', 'independent', 'w', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.DiffMaxChange = 1e-20;
opts.DiffMinChange = 1e-25;
opts.Display = 'Off';
opts.Lower = [C 1e-19 -1e-10 377];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.Robust = 'Bisquare';
opts.StartPoint = [C 0 0 377];
opts.TolFun = 0.001;
opts.Upper = [C 8e-07 4e-08 377];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Original', 'fitted', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'w', 'Interpreter', 'none' );
ylabel( 'S21', 'Interpreter', 'none' );
grid on


